# Generated by Django 2.2.5 on 2023-03-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookinfo_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='bool',
            new_name='book',
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='gender',
            field=models.SmallIntegerField(default=1, verbose_name={(1, 'male'), (2, 'female')}),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='people_info',
        ),
    ]
